none:
  mass_scale_set: [1.0]
  damping_scale_set: [1.0]

train_0:
  mass_scale_set: [0.5, 0.75, 1.0, 1.25, 1.5]
  damping_scale_set: [0.5, 0.75, 1.0, 1.25, 1.5]

test_0:
  mass_scale_set: [0.25, 0.375, 1.75, 2.0]
  damping_scale_set: [0.25, 0.375, 1.75, 2.0]