none:
  mass_scale_set: [1.0]
  damping_scale_set: [1.0]

train_0:
  mass_scale_set: [0.80, 0.90, 1.0, 1.15, 1.25]
  damping_scale_set: [0.80, 0.90, 1.0, 1.15, 1.25]

test_0:
  mass_scale_set: [0.60, 0.70, 1.50, 1.60]
  damping_scale_set: [0.60, 0.70, 1.50, 1.60]