#####################################
# Sequence encoder types
sequence_encoder:
  stacked:
    fc_hidden_sizes: (256, 128, 64,)
    activation: relu

  rnn:
    rnn_hidden_dim: 256
    fc_hidden_sizes: (128, 64,)
    activation: relu

#####################################
# Context encoder types
context_encoder:
  none:
    activation: none

#####################################
# Decoder types
decoder:
  single_head:
    num_layers: 4
    activation: swish
  multi_head:
    num_heads: 3
    num_layers: 4
    activation: swish

#####################################
# Dynamics model types
dynamics_model:
  dm:
    sequence_encoder_type: none
    context_encoder_type: none
    decoder_type: single_head

  cadm_stacked_singlehead:
    sequence_encoder_type: stacked
    context_encoder_type: none
    decoder_type: single_head

  cadm_rnn_singlehead:
    sequence_encoder_type: rnn
    context_encoder_type: none
    decoder_type: single_head

#####################################